- _includes/fundings.html
> Update funding section

- _includes/timeline.html
- _sass/layout/_timeline.scss
> Update timeline section

- _includes/timeline.html
> Update twitter-box display

- _data/sitetext.yml
> Update social links for Quentin's profile

- _sass/layout/_papers.scss
> Fixed social buttons bug

- _includes/team.html
- _sass/layout/_team.scss
> Fix alignment in Team section

- _includes/publications.html
- _papers/papers/2021.05.26_G.Abrevaya.md
> Add new paper

- _includes/nav.html
- _includes/publications.html
> Remove path-nav

- _data/collaborators.yml
- _includes/collaborators.html
- _includes/papers_grid.html
- _sass/layout/_collaborators.scss
- _sass/layout/_papers.scss
> Update papers-grid display

- _includes/team.html
> Center the last team member

- _includes/timeline.html
- _sass/layout/_timeline.scss
> Update Twitter timeline

- _data/alumni.yml
- _data/sitetext.yml
> Update Team status

- _data/alumni.yml
- _data/sitetext.yml
> New people

- _data/alumni.yml
- _data/sitetext.yml
> Moved Nicolas Coucke to Alumni

- _includes/nav.html
> Fixed Liquid error

- _data/alumni.yml
- _data/sitetext.yml
> Moved Hannah & Edoardo to Alumni

- _data/sitetext.yml
I've just added my LikedIn account and fixed an issue with the twitter logo.
> Add Germán's LinkedIn

- _data/sitetext.yml
> Added Marvel to team & updated Vincent's information

- _data/alumni.yml
- _data/sitetext.yml
> Moved Zahra to Alumni

- _data/sitetext.yml
> Corrected typo
